# Generated by Django 3.2.20 on 2023-08-09 09:24

import django.core.validators
from django.db import migrations, models
import geonode.icons.models


class Migration(migrations.Migration):

    dependencies = [
        ('icons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icon',
            name='path',
            field=models.ImageField(upload_to=geonode.icons.models.unique_filename, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png'])]),
        ),
    ]
