# Generated by Django 3.2.20 on 2023-08-09 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0085_alter_resourcebase_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='default_home_page',
            field=models.TextField(default=None, null=True, blank=True),
        ),
    ]
